FROM alpine:latest
RUN apk add --no-cache \
    curl \
    bash \
    git \
    typst

RUN apk add --no-cache \
    nodejs \
    npm \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Install Mermaid CLI globally
RUN npm install -g @mermaid-js/mermaid-cli



RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f

RUN apk add poppler-utils