FROM alpine:latest
RUN apk add --no-cache \
    curl \
    bash \
    git \
    typst



RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f

RUN apk add poppler-utils