
= Conclusão

Este trabalho apresentou o TechtonicCMS, um sistema de gerenciamento de conteúdo headless desenvolvido como prova de conceito de uma arquitetura que combina três contribuições técnicas principais: controle de acesso baseado em atributos com modelo formal de decisão, geração dinâmica de schemas GraphQL em tempo de execução, e armazenamento semi-estruturado unificado via JSONB com predicate pushdown para filtragem a nível de banco.

Os sete objetivos específicos propostos foram atingidos. A arquitetura headless nativa com GraphQL como interface exclusiva foi implementada e validada através de um caso de uso real de blog institucional com consumo multi-canal. O motor ABAC foi desenvolvido com suporte a políticas contextuais avaliando atributos do sujeito, recurso, ação e ambiente, com resolução determinística de conflitos por prioridade, cache persistente de avaliações e auditoria completa das decisões de autorização. O mecanismo de geração dinâmica de schemas reconstrói o contrato da API em tempo de execução a partir dos metadados de coleções, tornando novas operações disponíveis imediatamente sem reinicialização do serviço. A estratégia de armazenamento JSONB unificado eliminou a fragmentação do padrão EAV, viabilizando filtragem, ordenação e paginação diretamente no banco através de funções de extração customizadas. O sistema de autenticação duplo combina sessões JWT com refresh tokens single-use para usuários humanos e chaves de API com hash criptográfico para integrações machine-to-machine. A interface administrativa em SvelteKit consome a API GraphQL gerando formulários dinamicamente conforme o schema de cada coleção e respeitando as permissões ABAC do usuário autenticado.

O TechtonicCMS não se propõe a substituir soluções consolidadas como o Strapi em casos de uso gerais. Seu posicionamento é específico: onde o controle de acesso baseado em papéis é insuficiente para expressar regras contextuais como restrição por propriedade de recurso, estado de publicação e janela temporal, encontram no modelo ABAC uma arquitetura mais adequada. Da mesma forma, ambientes que demandam disponibilidade contínua se beneficiam da geração de schema em runtime, que elimina o downtime associado a alterações de tipos de conteúdo em sistemas que requerem recompilação ou reinicialização.

Como trabalhos futuros, identificam-se quatro direções principais. A realização de benchmarks comparativos formais contra alternativas como Strapi e Directus, medindo latência de autorização, throughput sob carga e impacto do predicate pushdown em volumes elevados de dados, transformaria as afirmações de performance do sistema de teóricas em empiricamente verificadas. A implementação de suporte a múltiplos bancos de dados ampliaria a aplicabilidade do sistema além do PostgreSQL. O desenvolvimento de um marketplace de políticas ABAC pré-configuradas para casos de uso comuns reduziria a barreira de adoção para equipes sem especialização em controle de acesso. Por fim, a evolução do mecanismo de schema dinâmico para suportar migrações incrementais de dados existentes, sem perda de integridade referencial, completaria o ciclo de vida de gestão de tipos de conteúdo em ambientes de produção.

O trabalho demonstra que é possível construir um CMS headless com controle de acesso granular e schema dinâmico em runtime utilizando tecnologias maduras do ecossistema .NET e PostgreSQL, com decisões arquiteturais fundamentadas na literatura e implementação verificável através do código-fonte disponível no repositório.